### ISSUE TITLE
node-sassのバージョンによりNode jsのバージョン指定が必要

### ISSUE THREAD

**Issue by mtb-beta** [hatena/Hatena-Blog-Theme-Boilerplate#15]
こちらのデザインテーマを動かした際の発見を報告させてもらいます。

node-sass が動作するNodeのバージョンは指定があります。

https://github.com/sass/node-sass#node-version-support-policy

現状のnode-sassのバージョンだと、対応するNodeのバージョンはNode 8です。
私の環境（Node 16がインストールされている）だと、`npm install` で詰まりました。

対応するNode 16に対応するnode-sass `7.0.1` にバージョンアップすると `npm install` および `npm run scss` が実行可能になったことを共有しておきます。

**Comment by ueday** [comment]
@mtb-beta ご報告ありがとうございます。本件、Node 16で動作するようチームで対応中です。

**Comment by ueday** [comment]
対応完了いたしました。ご報告ありがとうございました！ @mtb-beta
