### ISSUE TITLE
2024年2月1日から提供されているヘッダーについて

### ISSUE THREAD

**Issue by emigrant-song** [hatena/Hatena-Blog-Theme-Boilerplate#21]
お世話になっております。

従来のヘッダーですと `#globalheader-container` にて設定が出来ましたが、
新デザインのヘッダーではこのIDでの設定が利かないようです。

**Comment by airreader** [comment]
ご連絡いただきありがとうございます。
現在のところ、新しいグローバルヘッダではヘッダの色の変更を変更する機能は提供していません。

ご意見いただきありがとうございました。対応を検討いたします。

**Comment by emigrant-song** [comment]
新ヘッダーにて変更機能がない旨、承知いたしました。
