### ISSUE TITLE
Google Chrome is getting CORS errors

### ISSUE THREAD

**Issue by cateiru** [hatena/Hatena-Blog-Theme-Boilerplate#22]
## 発生している問題

- Chromeでは公開ウェブサイトからプライベートネットワークエンドポイントへの直接アクセスを非推奨としている
- そのため、現在の設定でアクセスするとCORSエラーとなってしまう
- `Access-Control-Request-Private-Network: true`と`Access-Control-Allow-Private-Network: true`を含む必用があるようです[^1]。
- また、その設定をしてもstylesheetの credential mode が `incluede`になっているようでアクセスできないようです[^2]。

[^1]: [Private Network Access: introducing preflights  |  Blog  |  Chrome for Developers](https://developer.chrome.com/blog/private-network-access-preflight/)
[^2]: [Link Tag Helper と Script Tag Helper (CORE)](http://surferonwww.info/BlogEngine/post/2021/08/09/link-tag-helper-and-script-tag-helper-for-aspnet-core.aspx)

## 解決策

- `Access-Control-Request-Private-Network: true`と`Access-Control-Allow-Private-Network: true` は https://github.com/vitejs/vite/discussions/7134#discussioncomment-3422554 で会話されている設定をすることで反映することができそうです。

```diff js
  ...
  css: {
    devSourcemap: true,
    postcss: {
      plugins: [autoprefixer()],
    },
  },
+  plugins: [
+    {
+      name: "configure-response-headers",
+      configureServer: (server) => {
+        server.middlewares.use((_req, res, next) => {
+          res.setHeader("Access-Control-Request-Private-Network", "true");
+          res.setHeader("Access-Control-Allow-Private-Network", "true");
+          next();
+        });
+      },
+    },
+  ],
};
```

- credential modeについては`crossorigin="anonymous"`とするとアクセスできるかと思います。

  ```html
  <script type="module" src="http://localhost:5173/@vite/client"></script>
  <link rel="stylesheet" crossorigin="anonymous" type="text/css" href="http://localhost:5173/scss/boilerplate.scss" />
  ```

**Comment by susisu** [comment]
@cateiru https://github.com/hatena/Hatena-Blog-Theme-Boilerplate/pull/23 で Access-Control-Allow-* ヘッダの付与と, `crossorigin` 属性の案内を追加しました. 報告ありがとうございました
