### ISSUE TITLE
httpsでのbrowser-sync実行方法について

### ISSUE THREAD

**Issue by Git-aTn** [hatena/Hatena-Blog-Theme-Boilerplate#7]
はてな担当様

新規にサブサイトを作成したらアドレスはhttpsでした。
npm start を実行してもbrowser-syncはhttpのアドレスしか認識してなく自動更新されません。

ローカル環境のアクセス先：
Local: http://localhost:3000
External: http://192.168.3.8:3000
管理画面のアクセス先：
UI: http://localhost:3001
UI External: http://192.168.3.8:3001

質問：
pacage.jnsnのbrowser-syncにどのようなオプションを追加すれば
httpsのサイトと同期できるか教えて頂けないでしょうか。

宜しくお願いいたします。

**Comment by ueday** [comment]
@Git-aTn お返事が遅れて申し訳ございません。 Browsersync が HTTPS のブログで正常に動作しないことを手元でも確認しました。
本件の対応について、チームで現在検討中です。ご不便をおかけしますが、何卒ご理解ください。

**Comment by Git-aTn** [comment]
さっそくのご確認ありがとうございます。お忙しいところ、ご検討恐れ入ります。
当方でもいろいろトライしてみましたが、上手く行きませんでした。
例えば、--https のオプションを追加するとローカル環境のアクセス先はhttpsに変わるのですが、管理画面のアクセス先はhttpのままでした。
以上、宜しくお願い致します。

**Comment by ueday** [comment]
@Git-aTn チームで検討した結果、Browsersync の自動リロードは今後サポート対象外といたします。大変申し訳ございません。
Browsersync を HTTPS で動かすオプションは存在するものの、SSLの証明書を手元で作成するか、もしくは安全でないスクリプトの読み込みを許容する必要があり、公式にサポートするのは困難という結論になりました。

ご不便をおかけしますが、 SCSS の保存後には手動でブラウザを更新していただきますようお願いいたします。

READMEのセットアップ方法については、こちらの pull request で修正しました: https://github.com/hatena/Hatena-Blog-Theme-Boilerplate/pull/8

**Comment by Git-aTn** [comment]
はてな開発チームのご担当様、上記ご回答ありがとうございます。

さっそく以下で動作確認しました。

■変更前：カスタマイズ　＞　ヘッダ　＞　タイトル下　に下記を貼り付けるる。
<link rel="stylesheet" href="http://localhost:3000/index.css"/>
<script async src='http://localhost:3000/browser-sync/browser-sync-client.js'></script>

■変更後：カスタマイズ　＞　{}デザインCSS　に下記を貼り付ける
@import url("http://localhost:3000/boilerplate.css");

SCSSを保存したら手動でリロードをする。

テストした結果、httpsアドレスでも画面は更新できました。

Browsersyncを公式サポート出来ないのは非常に残念ですが、
いつか対応できる日が来ることを期待いたします。

今後とも宜しくお願い致します。

**Comment by Git-aTn** [comment]
はてな開発チームの皆様、上記ご回答ありがとうございます。

さっそく、カスタマイズ　＞　{}デザインCSS　に下記を貼り付けてみました。
@import url("http://localhost:3000/boilerplate.css");

SCSSを保存→手動でリロード後、httpsアドレスでも画面は更新できました。

正直上記方法は従来に比べとても面倒ですが、諸般の事情で現時点ではBrowsersyncを公式サポート出来ないのはやむを得ないと理解致しました。

しかし、いつか対応できる日が来ることを期待いたします。

今後とも宜しくお願い致します。
